# -*- coding: utf-8 -*-

import numpy

feature_list = { 'feature_names' : numpy.array([
                                 "BoW",
                                 #"hashtagBOW",
                                 #"swearBOW",
                                 #"posTagBoW",
                                 #"numhashtag",
                                 #"isRetweet",
                                 #"capitalWordCount",
                                 #"adjective",
                                 #"emojiBOW",
                                 #"ironicBOW",
                                 #"sexistBOW",
                                 #"es_an",
                                 #"es_asf",
                                 #"es_asm",
                                 #"es_cds",
                                 #"es_ddf",
                                 #"es_ddp",
                                 #"es_dmc",
                                 #"es_is",
                                 #"es_om",
                                 #"es_or",
                                 #"es_pa",
                                 #"es_pr",
                                 #"es_ps",
                                 #"es_qas",
                                 #"es_rci",
                                 #"es_re",
                                 #"es_svp",
                                 #"emojiSentiment",
                                 #"emojiIncongruity",
                                 #"emojiCount",
                                 #"emojiPresence",
                                 #"questMark",
                                 #"hasDotDotDot",
                                 #"hasQuote",
                                 #"linkCount",
                                 #"textLength",
                                 #"emoticonCount",
                                 #"ironicWordCount",
                                 #"repeatedCharCount",
                                 #"mentionCount",
                                 #"pronounCount",
                                 #"linkPresence",
                                 #"sentimentScore",
                                 #"resolveURL",
                                 ])
                }